-- Sample tickers
INSERT OR IGNORE INTO tickers (symbol, name, exchange, sector, industry) VALUES
-- Technology
('AAPL', 'Apple Inc.', 'NASDAQ', 'Technology', 'Consumer Electronics'),
('MSFT', 'Microsoft Corporation', 'NASDAQ', 'Technology', 'Software'),
('GOOGL', 'Alphabet Inc.', 'NASDAQ', 'Technology', 'Internet Services'),
('NVDA', 'NVIDIA Corporation', 'NASDAQ', 'Technology', 'Semiconductors'),
('META', 'Meta Platforms Inc.', 'NASDAQ', 'Technology', 'Social Media'),
('AVGO', 'Broadcom Inc.', 'NASDAQ', 'Technology', 'Semiconductors'),
('ORCL', 'Oracle Corporation', 'NYSE', 'Technology', 'Software'),
('CRM', 'Salesforce Inc.', 'NYSE', 'Technology', 'Software'),
('AMD', 'Advanced Micro Devices Inc.', 'NASDAQ', 'Technology', 'Semiconductors'),
('INTC', 'Intel Corporation', 'NASDAQ', 'Technology', 'Semiconductors'),
('CSCO', 'Cisco Systems Inc.', 'NASDAQ', 'Technology', 'Networking'),
('ADBE', 'Adobe Inc.', 'NASDAQ', 'Technology', 'Software'),
('IBM', 'International Business Machines', 'NYSE', 'Technology', 'IT Services'),
('QCOM', 'Qualcomm Inc.', 'NASDAQ', 'Technology', 'Semiconductors'),
('TXN', 'Texas Instruments Inc.', 'NASDAQ', 'Technology', 'Semiconductors'),
('NOW', 'ServiceNow Inc.', 'NYSE', 'Technology', 'Software'),
('INTU', 'Intuit Inc.', 'NASDAQ', 'Technology', 'Software'),
('AMAT', 'Applied Materials Inc.', 'NASDAQ', 'Technology', 'Semiconductor Equipment'),
('MU', 'Micron Technology Inc.', 'NASDAQ', 'Technology', 'Semiconductors'),
('PANW', 'Palo Alto Networks Inc.', 'NASDAQ', 'Technology', 'Cybersecurity'),
('SHOP', 'Shopify Inc.', 'NYSE', 'Technology', 'E-Commerce Software'),
('SNOW', 'Snowflake Inc.', 'NYSE', 'Technology', 'Cloud Computing'),
('SQ', 'Block Inc.', 'NYSE', 'Technology', 'Fintech'),
('PLTR', 'Palantir Technologies Inc.', 'NYSE', 'Technology', 'Data Analytics'),
('UBER', 'Uber Technologies Inc.', 'NYSE', 'Technology', 'Ride-Sharing'),
-- Consumer Cyclical
('AMZN', 'Amazon.com Inc.', 'NASDAQ', 'Consumer Cyclical', 'Internet Retail'),
('TSLA', 'Tesla Inc.', 'NASDAQ', 'Consumer Cyclical', 'Auto Manufacturers'),
('HD', 'Home Depot Inc.', 'NYSE', 'Consumer Cyclical', 'Home Improvement'),
('NKE', 'Nike Inc.', 'NYSE', 'Consumer Cyclical', 'Footwear & Apparel'),
('MCD', 'McDonald''s Corporation', 'NYSE', 'Consumer Cyclical', 'Restaurants'),
('SBUX', 'Starbucks Corporation', 'NASDAQ', 'Consumer Cyclical', 'Restaurants'),
('LOW', 'Lowe''s Companies Inc.', 'NYSE', 'Consumer Cyclical', 'Home Improvement'),
('TGT', 'Target Corporation', 'NYSE', 'Consumer Cyclical', 'Discount Stores'),
('F', 'Ford Motor Company', 'NYSE', 'Consumer Cyclical', 'Auto Manufacturers'),
('GM', 'General Motors Company', 'NYSE', 'Consumer Cyclical', 'Auto Manufacturers'),
('BKNG', 'Booking Holdings Inc.', 'NASDAQ', 'Consumer Cyclical', 'Travel'),
('MAR', 'Marriott International Inc.', 'NASDAQ', 'Consumer Cyclical', 'Hotels'),
('ABNB', 'Airbnb Inc.', 'NASDAQ', 'Consumer Cyclical', 'Travel'),
-- Financial Services
('JPM', 'JPMorgan Chase & Co.', 'NYSE', 'Financial Services', 'Banks'),
('V', 'Visa Inc.', 'NYSE', 'Financial Services', 'Credit Services'),
('MA', 'Mastercard Inc.', 'NYSE', 'Financial Services', 'Credit Services'),
('GS', 'Goldman Sachs Group Inc.', 'NYSE', 'Financial Services', 'Capital Markets'),
('BAC', 'Bank of America Corp.', 'NYSE', 'Financial Services', 'Banks'),
('WFC', 'Wells Fargo & Company', 'NYSE', 'Financial Services', 'Banks'),
('MS', 'Morgan Stanley', 'NYSE', 'Financial Services', 'Capital Markets'),
('C', 'Citigroup Inc.', 'NYSE', 'Financial Services', 'Banks'),
('BLK', 'BlackRock Inc.', 'NYSE', 'Financial Services', 'Asset Management'),
('SCHW', 'Charles Schwab Corp.', 'NYSE', 'Financial Services', 'Brokerage'),
('AXP', 'American Express Company', 'NYSE', 'Financial Services', 'Credit Services'),
('PYPL', 'PayPal Holdings Inc.', 'NASDAQ', 'Financial Services', 'Fintech'),
('COF', 'Capital One Financial Corp.', 'NYSE', 'Financial Services', 'Banks'),
-- Healthcare
('JNJ', 'Johnson & Johnson', 'NYSE', 'Healthcare', 'Drug Manufacturers'),
('UNH', 'UnitedHealth Group Inc.', 'NYSE', 'Healthcare', 'Health Insurance'),
('LLY', 'Eli Lilly and Company', 'NYSE', 'Healthcare', 'Drug Manufacturers'),
('PFE', 'Pfizer Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers'),
('ABBV', 'AbbVie Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers'),
('MRK', 'Merck & Co. Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers'),
('TMO', 'Thermo Fisher Scientific Inc.', 'NYSE', 'Healthcare', 'Diagnostics & Research'),
('ABT', 'Abbott Laboratories', 'NYSE', 'Healthcare', 'Medical Devices'),
('BMY', 'Bristol-Myers Squibb Co.', 'NYSE', 'Healthcare', 'Drug Manufacturers'),
('GILD', 'Gilead Sciences Inc.', 'NASDAQ', 'Healthcare', 'Biotechnology'),
('MRNA', 'Moderna Inc.', 'NASDAQ', 'Healthcare', 'Biotechnology'),
('CVS', 'CVS Health Corporation', 'NYSE', 'Healthcare', 'Healthcare Plans'),
-- Energy
('XOM', 'Exxon Mobil Corporation', 'NYSE', 'Energy', 'Oil & Gas'),
('CVX', 'Chevron Corporation', 'NYSE', 'Energy', 'Oil & Gas'),
('COP', 'ConocoPhillips', 'NYSE', 'Energy', 'Oil & Gas'),
('SLB', 'Schlumberger Limited', 'NYSE', 'Energy', 'Oil & Gas Services'),
('EOG', 'EOG Resources Inc.', 'NYSE', 'Energy', 'Oil & Gas'),
('NEE', 'NextEra Energy Inc.', 'NYSE', 'Energy', 'Utilities - Renewables'),
('DUK', 'Duke Energy Corporation', 'NYSE', 'Energy', 'Utilities'),
-- Communication Services
('DIS', 'Walt Disney Co.', 'NYSE', 'Communication Services', 'Entertainment'),
('NFLX', 'Netflix Inc.', 'NASDAQ', 'Communication Services', 'Entertainment'),
('CMCSA', 'Comcast Corporation', 'NASDAQ', 'Communication Services', 'Telecom'),
('T', 'AT&T Inc.', 'NYSE', 'Communication Services', 'Telecom'),
('VZ', 'Verizon Communications Inc.', 'NYSE', 'Communication Services', 'Telecom'),
('SPOT', 'Spotify Technology S.A.', 'NYSE', 'Communication Services', 'Entertainment'),
('ROKU', 'Roku Inc.', 'NASDAQ', 'Communication Services', 'Entertainment'),
-- Consumer Defensive
('WMT', 'Walmart Inc.', 'NYSE', 'Consumer Defensive', 'Discount Stores'),
('PG', 'Procter & Gamble Co.', 'NYSE', 'Consumer Defensive', 'Household Products'),
('KO', 'Coca-Cola Company', 'NYSE', 'Consumer Defensive', 'Beverages'),
('PEP', 'PepsiCo Inc.', 'NASDAQ', 'Consumer Defensive', 'Beverages'),
('COST', 'Costco Wholesale Corp.', 'NASDAQ', 'Consumer Defensive', 'Discount Stores'),
('PM', 'Philip Morris International', 'NYSE', 'Consumer Defensive', 'Tobacco'),
('CL', 'Colgate-Palmolive Company', 'NYSE', 'Consumer Defensive', 'Household Products'),
-- Industrials
('BA', 'Boeing Company', 'NYSE', 'Industrials', 'Aerospace & Defense'),
('CAT', 'Caterpillar Inc.', 'NYSE', 'Industrials', 'Farm & Heavy Equipment'),
('UPS', 'United Parcel Service Inc.', 'NYSE', 'Industrials', 'Logistics'),
('RTX', 'RTX Corporation', 'NYSE', 'Industrials', 'Aerospace & Defense'),
('HON', 'Honeywell International Inc.', 'NASDAQ', 'Industrials', 'Conglomerates'),
('LMT', 'Lockheed Martin Corporation', 'NYSE', 'Industrials', 'Aerospace & Defense'),
('DE', 'Deere & Company', 'NYSE', 'Industrials', 'Farm & Heavy Equipment'),
('GE', 'GE Aerospace', 'NYSE', 'Industrials', 'Aerospace & Defense'),
-- Real Estate
('AMT', 'American Tower Corporation', 'NYSE', 'Real Estate', 'REIT'),
('PLD', 'Prologis Inc.', 'NYSE', 'Real Estate', 'REIT'),
('SPG', 'Simon Property Group Inc.', 'NYSE', 'Real Estate', 'REIT'),
-- ETFs
('SPY', 'SPDR S&P 500 ETF Trust', 'NYSE', 'ETF', 'Index Fund'),
('QQQ', 'Invesco QQQ Trust', 'NASDAQ', 'ETF', 'Index Fund'),
('DIA', 'SPDR Dow Jones Industrial Avg ETF', 'NYSE', 'ETF', 'Index Fund'),
('IWM', 'iShares Russell 2000 ETF', 'NYSE', 'ETF', 'Index Fund'),
('GLD', 'SPDR Gold Shares', 'NYSE', 'ETF', 'Commodities'),
('SLV', 'iShares Silver Trust', 'NYSE', 'ETF', 'Commodities'),
('VTI', 'Vanguard Total Stock Market ETF', 'NYSE', 'ETF', 'Index Fund'),
('ARKK', 'ARK Innovation ETF', 'NYSE', 'ETF', 'Thematic');

-- Admin user (password: admin123)
INSERT OR IGNORE INTO users (email, password_hash) VALUES
('admin@marketmonitor.com', 'PLACEHOLDER_HASH');
